#!/bin/bash

#DOCKER_TAG="andys/afs-2:exp1"
DOCKER_TAG="afs/fuseki"

if [[ $# == 0 ]]
then
    echo "No arguments for the Fuseki server" 1>&2
    exit 1
fi

# Check whether already running

## if [ $(docker inspect -f '{{.State.Running}}' $DOCKER_TAG) ]
## then
##     (
## 	echo "Fuseki container already running" 1>&2
## 	docker ps
##     )
##     exit 2
## fi

# Run with volumes.
# Map the the $MNT area to the Fuskei layout in the docker container.

MNT=$PWD/mnt
mkdir -p $MNT
mkdir -p $MNT/log
mkdir -p $MNT/data
CIDFILE="fuseki.cid"

## Or use --cidfile=$CIDFILE
## Different port: use "-p 8080:3030"

DETACH=${DETACH:--d}
NAME=Fuseki-$$

echo "Run $NAME"

docker run -p 3030:3030  --rm $DETACH --name $NAME \
       --mount "type=bind,src=$MNT/data,dst=/var/fuseki/data" \
       --mount "type=bind,src=$MNT/log,dst=/var/fuseki/log" \
       $DOCKER_TAG "$@" > $CIDFILE
